config/routes.rb
Rails.application.routes.draw do

  get 'metrics', to: 'metrics#index'

  get 'metrics/:layer', to: 'metrics#index',
                        as: 'metrics_layer',
                        constraints: {
                          layer: /[a-z_]+/
                        }

  get 'metrics/:layer/:name/measurements', to: 'measurements#index',
                                           as: 'metric_measurements',
                                           constraints: {
                                             layer: /[a-z_]+/,
                                             name:  /(([a-z_]+)\.?)+/
                                           }

  namespace :alerting do
    resources :policies do
      resources :conditions

      delete 'value_condition/:id', to: 'conditions#destroy',
                                    as: 'value_condition'
    end

    get 'incidents', to: 'incidents#index'
  end
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  belongs_to :policy

  TYPES = [
            ValueCondition,
            PercentileCondition,
            ExpirationCondition,
            ExistanceCondition
          ]

  def measurements
    raise "Not implemented"
  end

  def current_measurement
    raise "Not implemented"
  end

  def violated?
    raise "Not implemented"
  end
end

app/models/existance_condition.rb
class ExistanceCondition < Condition
end

app/models/expiration_condition.rb
class ExpirationCondition < Condition
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  belongs_to :policy

  def resolved?
    resolved_at.present?
  end
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
end

app/models/metric.rb
class Metric
  attr_accessor :layer, :name

  def initialize(layer, name)
    @layer = layer
    @name = name
  end

  def self.all
    Measurement.select(:layer, :name)
               .distinct
               .order(layer: :desc)
               .map { |m| Metric.new(m.layer, m.name) }
  end

  def self.where(*args)
    Measurement.where(*args).select(:layer, :name).distinct.order(layer: :desc)
  end

  def self.layers
    Measurement.select(:layer).distinct.map(&:layer)
  end

  def self.names
    Measurement.select(:name).distinct.map(&:name)
  end

end

app/models/percentile_condition.rb
class PercentileCondition < Condition
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  has_many :conditions
  has_many :incidents

  def violated?
    conditions.map(&:violated?).any?
  end
end

app/models/value_condition.rb
class ValueCondition < Condition
  def measurements
    Measurement.where(layer: layer, name: name).order(created_at: :asc)
  end

  def current_measurement
    measurements.last
  end

  def violated?
    return false unless current_measurement.present?

    if inverted?
      current_measurement.value < value
    else
      current_measurement.value > value
    end
  end
end

app/controllers/alerting/conditions_controller.rb
module Alerting
  class ConditionsController < ApplicationController
    before_action :validate_type

    def new
      @policy = Policy.find(params[:policy_id])
      @condition = Condition.new
    end

    def create
      @policy = Policy.find(params[:policy_id])
      @condition = @policy.conditions.build(condition_params)

      if @condition.save
        redirect_to alerting_policies_path
      else
        render :new
      end
    end

    def edit
      # Skip for now
    end

    def update
      # Skip for now
    end

    def destroy
      @condition = Condition.find(params[:id])
      @condition.destroy!

      redirect_to alerting_policies_path
    end

    private

    def validate_type
      unless Condition::TYPES.map(&:to_s).include? params[:type]
        params[:type] = Condition::TYPES.first.to_s
      end
    end

    def condition_params
      if params[:condition].present?
        params[:condition].permit(:layer, :name, :type, :value, :percentile, :inverted)
      else
        {}
      end
    end
  end
end

app/controllers/alerting/incidents_controller.rb
module Alerting
  class IncidentsController < ApplicationController
    def index
      @incidents = Incident.all#.where(resolved_at: nil)
    end
  end
end

app/controllers/alerting/policies_controller.rb
module Alerting
  class PoliciesController < ApplicationController
    def index
      @policies = Policy.all
    end

    def new
      @policy = Policy.new
    end

    def create
      @policy = Policy.new(policy_params)

      if @policy.save
        redirect_to alerting_policies_path
      else
        render :new
      end
    end

    def show
    end

    def edit
      @policy = Policy.find(params[:id])
    end

    def update
      @policy = Policy.find(params[:id])

      if @policy.update_attributes(policy_params)
        redirect_to alerting_policies_path
      else
        render :edit
      end
    end

    def destroy
      policy = Policy.find(params[:id])
      policy.destroy

      redirect_to alerting_policies_path
    end

    private

    def policy_params
      if params[:policy].present?
        params[:policy].permit(:name, :description)
      else
        {}
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  def index
    @metrics = Metric.where(layer: params[:layer])
    @measurements = Measurement.where('created_at > ?', Time.now - 1.hour)
                               .where(layer: params[:layer], name: params[:name])
                               .order(created_at: :asc)

    if params[:chart]
      @series = @measurements.group_by(&:host)
    else
      @measurements = @measurements.page(params[:page])
    end
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  def index
    redirect_to metrics_layer_path(layer: 'physical') if params[:layer].nil?

    @metrics = Metric.where(layer: params[:layer])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def name_for_condition_type(type)
    case type.new
    when ValueCondition
      'Value'
    when PercentileCondition
      'Percentile'
    when ExpirationCondition
      'Expiration'
    when ExistanceCondition
      'Existance'
    else
      "Type #{type} not defined."
    end
  end

  def description_for_condition(condition)
    case condition.type
    when 'ValueCondition'
      "Alert if
      #{content_tag(:strong, "#{condition.layer}.#{condition.name}")}
      goes #{condition.inverted ? 'below' : 'over'}
      #{content_tag(:strong, condition.value)}
      ".html_safe
    when 'PercentileCondition'
      'Not implemented'
    when 'ExpirationCondition'
      'Not implemented'
    when 'ExistanceCondition'
      'Not implemented'
    else
      raise "Type #{condition.type} not defined."
    end
  end
end

app/views/alerting/conditions/_existance_condition_form.slim
| _existance_condition_form.slim

app/views/alerting/conditions/_expiration_condition_form.slim
| _expiration_condition_form.slim

app/views/alerting/conditions/_percentile_condition_form.slim
| _percentile_condition_form.slim

app/views/alerting/conditions/_value_condition_form.slim
= form_for [:alerting, @policy, @condition] do |f|
  .row
    .col-sm-3
      .form-group
        = f.label :layer, 'Layer'
        = f.select :layer, Metric.layers, { prompt: true }, class: 'form-control'
    .col-sm-3
      .form-group
        = f.label :name, 'Name'
        = f.select :name, Metric.names, { prompt: true }, class: 'form-control'
    .col-sm-3
      .form-group
        = f.label :inverted, 'Limit direction'
        = f.select :inverted, [['over', false], ['below', true]], {}, class: 'form-control'
    .col-sm-3
      .form-group
        = f.label :value, 'Value'
        = f.number_field :value, class: 'form-control'

  .row
    .col-sm-3
     .form-group
      = f.hidden_field :type, value: params[:type]
      = f.submit class: 'btn btn-primary btn-block'

app/views/alerting/conditions/edit.html.slim
h1 Edit policy condition

app/views/alerting/conditions/new.html.slim
h1 New policy condition

= render "#{params[:type].underscore}_form"

app/views/alerting/incidents/index.html.slim
h1 Incidents

- if @incidents.any?
  table.table
    thead
      tr
        th Violated policy
        th Violated conditions
        th Violated at
        th Last violated at
        th Resolved
    tbody
      - @incidents.each do |incident|
        tr
          td = incident.policy.name
          td
            - incident.policy.conditions.select { |c| c.violated? }.each do |condition|
              div
                = "#{condition.layer}.#{condition.name}"
                | &nbsp;
                = condition.inverted ? '<' : '>'
                | &nbsp;
                = condition.value

          td = incident.created_at
          td = incident.last_available_at
          td = incident.resolved?

- else
  p Currently there are no incidents.

app/views/alerting/policies/_form.slim
= form_for [:alerting, policy] do |f|
  .form-group
    = f.text_field :name, placeholder: 'Name', class: 'form-control'

  .form-group
    = f.text_field :description, placeholder: 'Description', class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-primary'

app/views/alerting/policies/edit.html.slim
h1 Edit policy

= render 'form', policy: @policy

app/views/alerting/policies/index.html.slim
h1 Policies

.row
  - if @policies.any?
    - @policies.each do |policy|
      .col-xs-12
        .panel.panel-default
          .panel-heading
             h3.panel-title = policy.name
             span = policy.description
          .panel-body
            - if policy.conditions.any?
              ul.list-group
                - policy.conditions.each do |condition|
                  li.list-group-item
                    .row
                      .col-sm-10 = description_for_condition(condition)
                      .col-sm-2 = button_to 'Delete', [:alerting, policy, condition], method: :delete, class: 'btn btn-danger btn-xs'
            - else
              p There are no conditions for this policy.
          .panel-footer
            .btn-group
              button.btn.btn-xs.btn-default.dropdown-toggle data-toggle="dropdown"
                | New condition
                | &nbsp;
                span.caret
              ul.dropdown-menu
                - Condition::TYPES.each do |type|
                  li = link_to "#{name_for_condition_type(type)} condition", new_alerting_policy_condition_path(policy, type: type)

            = link_to 'Edit', edit_alerting_policy_path(policy), class: 'btn btn-default btn-xs'
            | &nbsp;
            = button_to 'Delete', [:alerting, policy], method: :delete, class: 'btn btn-danger btn-xs'

  - else
    .col-xs-12
      .alert.alert-info  There are no policies.

  .col-xs-12
    = link_to 'New policy', new_alerting_policy_path, class: 'btn btn-primary'

app/views/alerting/policies/new.html.slim
h1 New alert policy

= render 'form', policy: @policy

app/views/layouts/application.html.slim
doctype html
html
  head
    title Mayday, Mayday!

    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    header.header
      .navbar.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
            button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            = link_to '#', class: 'navbar-brand' do
              = icon('fire')

          #navbar.collapse.navbar-collapse
            ul.nav.navbar-nav
              li = link_to 'Metrics', metrics_path
              li.dropdown
                = link_to '#', class: 'dropdown-toggle', :'data-toggle' => 'dropdown', role: 'button', :'aria-haspopup' => 'true', :'aria-expanded' => 'false' do
                  | Alerting
                  span.caret
                ul.dropdown-menu
                  li
                    = link_to 'Policies', alerting_policies_path
                    = link_to 'Incidents', alerting_incidents_path
                    = link_to 'Routing', '#'
              li = link_to 'Dashboards', '#'
              li = link_to 'Reports', '#'

    .container
      = yield

app/views/measurements/index.html.slim
br

ul.nav.nav-tabs
  - ['physical', 'service', 'application', 'business'].each do |layer|
    li class="#{'active' if params[:layer] == layer}" = link_to layer.capitalize, metrics_layer_path(layer: layer)

br

.row
  .col-xs-3
    - if @metrics.any?
      - @metrics.each do |metric|
        = link_to metric.name, metric_measurements_path(layer: metric.layer, name: metric.name), class: "btn  btn-block #{params[:name] == metric.name ? 'btn-primary' : 'btn-default'}"

  .col-xs-9
    .chart#chart style="width:100%; height:400px;"
    javascript:
      var chart;

      function loadData() {
        $.ajax({
          url: "#{metric_measurements_path(layer: params[:layer], name: params[:name], chart: true, format: :json)}",
          success: function(series) {
            for(var i=0; i<series.length; i++){
              chart.addSeries({
                name: series[i].name,
                data: series[i].data
              });
            }
          },
          cache: false
        });
      }

      $(function() {
        chart = new Highcharts.Chart({
          chart: {
            renderTo: 'chart'
          },
          title: {
            text: "#{params[:name]}",
          },
          xAxis: {
            type: 'datetime',
            tickPixelInterval: 150,
            maxZoom: 20 * 1000
          }
        });

        loadData();
      });

    br

    table.table
      thead
        tr
          th Layer
          th Metric
          th Value
          th Host
          th Valid until
          th Created at
      tbody
        - @measurements.each do |measurement|
          tr
            td = measurement.layer
            td = measurement.name
            td = measurement.value
            td = measurement.host
            td = measurement.valid_until
            td = measurement.created_at

    nav
      ul.pagination
        - if @measurements.previous_page
          li
            = link_to metric_measurements_path(layer: params[:layer], name: params[:name], page: @measurements.previous_page) do
              span &laquo;

        - 1.upto(@measurements.total_pages) do |page|
          li class="#{'active' if page == @measurements.current_page}" = link_to page, metric_measurements_path(layer: params[:layer], name: params[:name], page: page)

        - if @measurements.next_page
          li
            = link_to metric_measurements_path(layer: params[:layer], name: params[:name], page: @measurements.next_page) do
              span &raquo;

app/views/metrics/index.html.slim
h1 Metrics

ul.nav.nav-tabs
  - ['physical', 'service', 'application', 'business'].each do |layer|
    li class="#{'active' if params[:layer] == layer}" = link_to layer.capitalize, metrics_layer_path(layer: layer)

br

.row
  .col-xs-3
    - if @metrics.any?
      - @metrics.each do |metric|
        = link_to metric.name, metric_measurements_path(layer: metric.layer, name: metric.name), class: "btn  btn-block #{params[:name] == metric.name ? 'btn-primary' : 'btn-default'}"